name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist

  pypi-publish:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: ./dist